[package]
name = "sync_pool"
version = "0.1.0"
authors = ["Jacob Zuo <chopinsky@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
